### ISSUE TITLE
Click to edit cluster title fails on Safari

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/pix-plot#165]
Safari doesn't seem to be triggering the "edit cluster name" function in the Admin view -- the cursor remains a pointer and no text entry is possible.

**Comment by duhaime** [comment]
I think this is rectified if we add:

```css
[contenteditable] {
    -webkit-user-select: text;
    user-select: text;
}
```

to the styles!
